/*WAP FOR BELOW REQ 
1.CREATE AN INTERFACE ANIMAL WITH THE METHOD NOISE
2.CREATE 3 IMPLEMETATION CLASSES LION,DOG,CAT WHICH IMP NOISE METHOD,LION ROARS,DOG BARGS,CAT MEOW..
3.CREATE A CLASS ZOO,WITH THE STATIC METHOD MAKES SOUND,THESE METHOD IS GENERELIZED METHOD TO ALL THE TYPES OF ANIMAL,CALL NOISE METHOD 
4.CREATE A MAIN CLASS WITH MAIN METHOD,CALL MAKES SOUND AND PASS DIFFERENT TYPES OF ANIMAL OBJECTS. */
 interface animal
{
	void noise();
}
