/* 1.WAP TO DEFINE AN ABSTRACT METHOD IN ABSTRACT CALSS ,OVERRIDE METHOD AND DEFINE OWN METHOD,PERFORM UP AND DOWN CASTING
2.WAP TO DEFINE A METHOD IN INTERFACE,IMPLEMENT THE METHOD  AND OWN METHOD,PERFORM UP AND DOWN CASTING */
abstract class start
{
	 abstract public void run();
	
}
